App\Domain\DTO\TicketsDTO:
    constraints:
        - App\Validator\Constraints\ContainsDateBeforeDay: ~
        - App\Validator\Constraints\ContainsDateBeforeHour: ~
    properties:
        name:
            - NotBlank:
                message: 'Ce champ ne doit pas être vide.'
            - Regex:
                pattern: '/\d/'
                match:   false
                message: 'Votre nom ne doit contenir que des lettres.'
            - Length:
                max: 50
                min: 2
                minMessage: La valeur du nom est trop courte. Votre nom doit contenir au moins {{ limit }} caractères.
                maxMessage: La valeur du nom est trop longue. Votre nom doit contenir moins de {{ limit }} caractères.
        firstname:
            - NotBlank:
                message: 'Ce champ ne doit pas être vide.'
            - Regex:
                pattern: '/\d/'
                match:   false
                message: 'Votre prénom ne doit contenir que des lettres.'
            - Length:
                max: 50
                min: 2
                minMessage: La valeur du prénom est trop courte. Votre nom doit contenir au moins {{ limit }} caractères.
                maxMessage: La valeur du prénom est trop longue. Votre nom doit contenir moins de {{ limit }} caractères.
        dateofbirth:
            - NotBlank:
                message: 'Ce champ ne doit pas être vide.'
        tarif:
            - NotBlank:
                message: 'Ce champ ne doit pas être vide.'
        dateofbooking:
            - NotBlank:
                message: 'Ce champ ne doit pas être vide.'
            - App\Validator\Constraints\ContainsDateFormat: ~
            - App\Validator\Constraints\ContainsDateCloseDay: ~
            - App\Validator\Constraints\ContainsDateFreeDay: ~

        country:
            - NotBlank:
                message: 'Ce champ ne doit pas être vide.'