homepage:
    path: /
    controller: App\Controller\homepageController::index

accounts:
    path: /reservation
    controller: App\Controller\accountsController::accountsInfo

command:
    path: /reservation/commande
    controller: App\Controller\commandController::commandInfo